# docker file for local development and debugging
version: "3.3"
services:
  proddb:
    build: proddb
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: app
    volumes:
      - proddata:/var/lib/postgresql/data
  studentdb:
    build: studentdb
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: app
    volumes:
      - studentdata:/var/lib/postgresql/data
  appsrv:
    build:
      context: ./appsrv
      dockerfile: Dockerfile.jvm
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
  nginx:
    build: nginx
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 4000:80
    depends_on:
      - appsrv
volumes:
  proddata:
  studentdata:
