# this docker file ist deployed on the remote server

version: '3.3'
services:
  proddb:
    image: leodatabaselearner-proddb
    restart: always
    environment:
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - proddata:/var/lib/postgresql/data
  studentdb:
    image: leodatabaselearner-studentdb
    restart: always
    environment:
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    expose:
      - 5433
    volumes:
      - studentdata:/var/lib/postgresql/data
  appsrv:
    image: leocloud-appsrv
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
  nginx:
    image: leocloud-nginx
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 80:80
    depends_on:
      - appsrv
volumes:
  proddata:
  studentdata:
